/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://aa27ho6uzzes3kvjt4dz7vpefa.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-v77k4xuannd5nnzhvvwhkq5msm",
    "aws_cognito_identity_pool_id": "us-east-2:e3ea1514-c7ba-4364-a789-0f6e76ed2f77",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_8emuGqDkM",
    "aws_user_pools_web_client_id": "g1qn6hs6ic3jbobj8d0h9b30j",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "jamarjonesportfolio20bdcca308cd4e34a437ffb95e2a94308-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
